version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n-video-repurposing
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678}
      - GENERIC_TIMEZONE=${TIMEZONE:-UTC}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-admin123}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-encryption-key}
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      # Enable API access
      - N8N_API_BASE_URL=http://localhost:5678/api/v1
      - N8N_DISABLE_UI=false
    volumes:
      - n8n_data:/home/node/.n8n
      - video_files:/home/node/n8n_video_files
      - ./workflows:/opt/n8n/workflows
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: n8n-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - n8n

volumes:
  n8n_data:
  video_files: 